package jfxFilesRenamer.Enumerators;

public enum Actions {
	SCANFOLDER,
	ADDFILES,
	APPLY,
	REPLACETEXT,
	REPLACELETTERSCASE,
	REPLACEMULTIPLEOCCURENCES,
	REPLACEMISCELLANEOUS,
	REMOVETEXT,
	REMOVETEXTBETWEEN,
	REMOVEPOSITION,
	REMOVEEXTRASPACES,
	REMOVEBRACKETS,
	INSERTTEXT,
	INSERTNUMBER,
	INSERTMISCELLANEOUS,
	RENAMENUMBER,
	RENAMEMISCELLANEOUS,
	EXTADD,
	EXTREPLACE,
	EXTREMOVE,
	EXTLETTERSCASE
	
}
