package jfxFilesRenamer.Enumerators;

public enum ObservableList_Fields {
	FILEID,
	FILEORIGINAL,
	FILEORIGINALWITHOUTEXTENSION,
	FILERENAMED,
	FILESTATUS,
	FILEEXTENSION,
	FILEPATH,
	PARENTFOLDER,
	READYFORRENAME,
	APPLIEDRENAME
}
