package jfxFilesRenamer.Enumerators;

public enum Validation {
	NEWNAMEEMPTY,
	NEWNAMEHASILLEGALCHARACTERS,
	NEWNAMEALREADYEXISTS,
	NEWNAMEEQUALSORIGINALNAME,
	VALID,
	INVALID,
	NOTRENAMED,
	RENAMEAPPLIED
}